package Clases;

// default package
// Generated 17 dic 2023, 17:10:06 by Hibernate Tools 5.2.13.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Astronauta generated by hbm2java
 */
@Entity
@Table(name = "astronauta", catalog = "nasa_db")
public class Astronauta {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_Astronauta")
    private int ID_Astronauta;

    @Column(name = "Nombre")
    private String Nombre;

    @Column(name = "Apellidos")
    private String Apellidos;

    @Column(name = "Fecha_Nacimiento")
    private Date Fecha_Nacimiento;

    @Column(name = "Fecha_Ingreso_NASA")
    private Date Fecha_Ingreso_NASA;

    @Column(name = "Sexo")
    private String Sexo;

    @Column(name = "Nacionalidad")
    private String Nacionalidad;

    @Column(name = "Num_Vuelos_Espaciales")
    public int Num_Vuelos_Espaciales;

    @Column(name = "Horas_Espacio")
    public BigDecimal Horas_Espacio;

    @Column(name = "ID_Equipo")
    public Equipo equipo;

    @Column(name = "ID_Cargo")
    public int ID_Cargo;

    public Astronauta(int ID_Astronauta, String Nombre, String Apellidos, Date Fecha_Nacimiento, Date Fecha_Ingreso_NASA, String Sexo, String Nacionalidad, int Num_Vuelos_Espaciales, BigDecimal Horas_Espacio, Equipo ID_Equipo, int ID_Cargo) {
        this.ID_Astronauta = ID_Astronauta;
        this.Nombre = Nombre;
        this.Apellidos = Apellidos;
        this.Fecha_Nacimiento = Fecha_Nacimiento;
        this.Fecha_Ingreso_NASA = Fecha_Ingreso_NASA;
        this.Sexo = Sexo;
        this.Nacionalidad = Nacionalidad;
        this.Num_Vuelos_Espaciales = Num_Vuelos_Espaciales;
        this.Horas_Espacio = Horas_Espacio;
        this.equipo = ID_Equipo;
        this.ID_Cargo = ID_Cargo;
    }
    
    public Astronauta(){
        
    }

    public int getID_Astronauta() {
        return ID_Astronauta;
    }

    public void setID_Astronauta(int ID_Astronauta) {
        this.ID_Astronauta = ID_Astronauta;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public String getApellidos() {
        return Apellidos;
    }

    public void setApellidos(String Apellidos) {
        this.Apellidos = Apellidos;
    }

    public Date getFecha_Nacimiento() {
        return Fecha_Nacimiento;
    }

    public void setFecha_Nacimiento(Date Fecha_Nacimiento) {
        this.Fecha_Nacimiento = Fecha_Nacimiento;
    }

    public Date getFecha_Ingreso_NASA() {
        return Fecha_Ingreso_NASA;
    }

    public void setFecha_Ingreso_NASA(Date Fecha_Ingreso_NASA) {
        this.Fecha_Ingreso_NASA = Fecha_Ingreso_NASA;
    }

    public String getSexo() {
        return Sexo;
    }

    public void setSexo(String Sexo) {
        this.Sexo = Sexo;
    }

    public String getNacionalidad() {
        return Nacionalidad;
    }

    public void setNacionalidad(String Nacionalidad) {
        this.Nacionalidad = Nacionalidad;
    }

    public int getNum_Vuelos_Espaciales() {
        return Num_Vuelos_Espaciales;
    }

    public void setNum_Vuelos_Espaciales(int Num_Vuelos_Espaciales) {
        this.Num_Vuelos_Espaciales = Num_Vuelos_Espaciales;
    }

    public BigDecimal  getHoras_Espacio() {
        return Horas_Espacio;
    }

    public void setHoras_Espacio(BigDecimal Horas_Espacio) {
        this.Horas_Espacio = Horas_Espacio;
    }

    public int getID_Equipo() {
        return equipo.getIdEquipo();
    }

    public void setID_Equipo(Equipo ID_Equipo) {
        this.equipo = ID_Equipo;
    }

    public int getID_Cargo() {
        return ID_Cargo;
    }

    public void setID_Cargo(int ID_Cargo) {
        this.ID_Cargo = ID_Cargo;
    }

    @Override
    public String toString() {
        return "Astronauta{" + "ID_Astronauta=" + ID_Astronauta + ", Nombre=" + Nombre + ", Apellidos=" + Apellidos + ", Fecha_Nacimiento=" + Fecha_Nacimiento + ", Fecha_Ingreso_NASA=" + Fecha_Ingreso_NASA + ", Sexo=" + Sexo + ", Nacionalidad=" + Nacionalidad + ", Num_Vuelos_Espaciales=" + Num_Vuelos_Espaciales + ", Horas_Espacio=" + Horas_Espacio + ", equipo=" + equipo + ", ID_Cargo=" + ID_Cargo + '}';
    }
    
    
    
    
}