package Clases;

// default package
// Generated 17 dic 2023, 17:10:06 by Hibernate Tools 5.2.13.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Habilidad generated by hbm2java
 */
@Entity
@Table(name = "habilidad", catalog = "nasa_db")
public class Habilidad implements java.io.Serializable {

	private int idHabilidad;
	private String nombreHabilidad;
	private Set<Astronauta> astronautas = new HashSet<Astronauta>(0);

	public Habilidad() {
	}

	public Habilidad(int idHabilidad) {
		this.idHabilidad = idHabilidad;
	}

	public Habilidad(int idHabilidad, String nombreHabilidad, Set<Astronauta> astronautas) {
		this.idHabilidad = idHabilidad;
		this.nombreHabilidad = nombreHabilidad;
		this.astronautas = astronautas;
	}

	@Id

	@Column(name = "ID_Habilidad", unique = true, nullable = false)
	public int getIdHabilidad() {
		return this.idHabilidad;
	}

	public void setIdHabilidad(int idHabilidad) {
		this.idHabilidad = idHabilidad;
	}

	@Column(name = "Nombre_Habilidad")
	public String getNombreHabilidad() {
		return this.nombreHabilidad;
	}

	public void setNombreHabilidad(String nombreHabilidad) {
		this.nombreHabilidad = nombreHabilidad;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "habilidads")
	public Set<Astronauta> getAstronautas() {
		return this.astronautas;
	}

	public void setAstronautas(Set<Astronauta> astronautas) {
		this.astronautas = astronautas;
	}

}
