package Clases;

// default package
// Generated 17 dic 2023, 17:10:06 by Hibernate Tools 5.2.13.Final
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Nave generated by hbm2java
 */
@Entity
@Table(name = "Nave")
public class Nave implements Serializable {

    @Id
    @Column(name = "ID_Nave")
    private int idNave;

    @Column(name = "Nombre_Nave")
    private String nombreNave;

    @ManyToOne
    @JoinColumn(name = "ID_Base", referencedColumnName = "ID_Base", foreignKey = @ForeignKey(name = "FK_Nave_Base"))
    private Base base;

    public Nave(int idNave, String nombreNave, Base base) {
        this.idNave = idNave;
        this.nombreNave = nombreNave;
        this.base = base;
    }

    @Override
    public String toString() {
        return "Nave{" + "idNave=" + idNave + ", nombreNave=" + nombreNave + ", base=" + base + ", equipos=" + equipos + '}';
    }
    
    @ManyToMany
    @JoinTable(
        name = "Nave_Equipo",
        joinColumns = @JoinColumn(name = "ID_Nave"),
        inverseJoinColumns = @JoinColumn(name = "ID_Equipo"),
        foreignKey = @ForeignKey(name = "FK_Nave_Equipo_Nave"),
        inverseForeignKey = @ForeignKey(name = "FK_Nave_Equipo_Equipo")
    )
    private Set<Equipo> equipos = new HashSet<>();

    public Nave(){
        
    }

    public int getIdNave() {
        return idNave;
    }

    public void setIdNave(int idNave) {
        this.idNave = idNave;
    }

    public String getNombreNave() {
        return nombreNave;
    }

    public void setNombreNave(String nombreNave) {
        this.nombreNave = nombreNave;
    }

    public Base getBase() {
        return base;
    }

    public void setBase(Base base) {
        this.base = base;
    }
    
}
